import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Footer from "../components/Footer";
import { Toaster } from "react-hot-toast";
import { NextAuthProvider } from "../providers/next-auth.provider";
import Providers from "../providers/react-query.provider";

const encode = Encode_Sans({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${encode.className}`}>
        <NextAuthProvider>
          <Providers>
            <Toaster></Toaster>

            <div className="container max-w-[1400px]">
              <Navbar></Navbar>
              {children}

              <Footer></Footer>
            </div>
          </Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}
